version: '3.9'

services:
  postgres:
    image: postgres:14.4-alpine
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: local
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:7.0.4-alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis:/var/lib/redis/data

volumes:
  postgres:
    driver: local
  redis:
    driver: local
